port module Routes exposing (..)

-- Do not edit this file manually.

import Json.Decode exposing (Value)


port get : String -> Cmd msg


port post : Value -> Cmd msg


port patch : Value -> Cmd msg


port delete : String -> Cmd msg

ROUTES
